// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEf_QeTI-9Wss05Z5t6nofi5g9q-v8TCI',
    appId: '1:100203574419:android:27505a95afb53c9f6bc966',
    messagingSenderId: '100203574419',
    projectId: 'tempo-17b12',
    storageBucket: 'tempo-17b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP2QCcqoYy6eTfW7LIuQYWXhFF73GtwkA',
    appId: '1:100203574419:ios:e1203528af3eb4c06bc966',
    messagingSenderId: '100203574419',
    projectId: 'tempo-17b12',
    storageBucket: 'tempo-17b12.appspot.com',
    androidClientId: '100203574419-b26n0n1sum3f2hjcfnqdqskvjffacqa9.apps.googleusercontent.com',
    iosClientId: '100203574419-ujlaodkrfiqgsc0gsto1i6igcrrnlcrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempest',
  );
}
